name: facebook_app_events_example
publish_to: none
description: Demonstrates how to use the facebook_app_events plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.5
  app_tracking_transparency: ^2.0.2+1
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  facebook_app_events: 
    git: 
      url: git@github.com:ericmartineau/flutter_facebook_app_events.git
      ref: trippi_app
flutter: 
  uses-material-design: true
