name: facebook_app_events
version: 0.14.7
homepage: https://github.com/oddbit/flutter_facebook_app_events
description: Flutter plugin for Facebook App Events, an app measurement solution that provides insight on app usage and user engagement in Facebook Analytics.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: id.oddbit.flutter.facebook_app_events
        pluginClass: FacebookAppEventsPlugin
      ios: 
        pluginClass: FacebookAppEventsPlugin
